language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
    - 5
    - 6
    - stable

deploy:
    provider: npm
    api_key:
        secure: bb03c315-de88-49a4-b988-396278221f41
        on:
            tags: true
